### ISSUE TITLE
Odd mis-asignment

### ISSUE THREAD

**Issue by jonocarroll** [mitchelloharawild/icons#1]
Maybe it's just me, but this doesn't seem like the right output

```
fa_birthday_cake()
#> [1] "fa:xbox"
```

`icon::fa("birthday_cake")` produces the appropriate `"fa:birthday_cake"`.

None of these render, but that's very likely my setup.

**Comment by earowang** [comment]
In the console, it only prints out the string. The icon only appear in the rmarkdown file.

**Comment by jonocarroll** [comment]
Cheers. I get a link in my rendered markdown but I haven't tried playing with it too much.

I presume `xbox` is somewhat incorrect for `birthday_cake` nonetheless.

**Comment by earowang** [comment]
```r
fa_birthday_cake()
#> [1] "fa:xbox"
```

This one is most likely a bug.

**Comment by earowang** [comment]
thanks mitch.
