### ISSUE TITLE
Add new fonticon version 5.0.11?

### ISSUE THREAD

**Issue by maelle** [mitchelloharawild/icons#11]
contains the R icon 🎊

**Comment by mitchelloharawild** [comment]
Resolved in #13
Hurray! :tada:

**Comment by privefl** [comment]
I've just reinstalled this package and it says that 
> 'fa_r' is not an exported object from 'namespace:icon'

It was working fine three weeks ago.

**Comment by mitchelloharawild** [comment]
Font awesome changed the name of the icon.
https://twitter.com/fontawesome/status/992390923689648128?s=20

Please use fa_r_project(), I've added a more informative error in 4f6150552a2c1776168a3202afa5c02c722f03e4
