### ISSUE TITLE
Technotes blog post about icon on rOpenSci blog?

### ISSUE THREAD

**Issue by maelle** [mitchelloharawild/icons#14]
@mitchelloharawild nice work on the update and on your announcement tweet! :wink:

Would you be interested in writing a short narrative as a tech note on rOpenSci blog? 

* Technically, here are other tech notes https://github.com/ropensci/roweb2/tree/master/content/technotes you'd submit your post as a Pull Request. Tech notes are not on a schedule so can be posted whenever. Your PR would be reviewed by an rOpenSci staff member (probably Stefanie cc-ed below). Tech notes are [more](https://github.com/ropensci/roweb2/blob/master/content/technotes/2016-10-05-graphql-release-10.md) or [less](https://github.com/ropensci/roweb2/blob/master/content/technotes/2018-02-20-webmockr-intro.md) short.

* Ideally your post would present `icon` with a screenshot like in your tweet and
    * Mention the origin of the presence of the R icon in font-awesome latest release. [this issue](https://github.com/FortAwesome/Font-Awesome/issues/3862) and [this tweet which helped a lot to get the request ranked higher](https://twitter.com/LockeData/status/987286302721806337)
    * Remind the package was created at ozunconf17, and mention by name the other authors/contributors.

* You could also explain what the future development plans of `icon` are (submission to CRAN? links to open issues in the repo in case help is welcome?), and well whatever you'd like to say about the package.

cc @stefaniebutland (rOpenSci community manager)

**Comment by mitchelloharawild** [comment]
Sure, I can write a small discussion about `icon` for the blog. :smiley:

**Comment by maelle** [comment]
Very cool, thank you! Ask me any question you might have about the technote format. I will review your first draft and Stefanie the final version. I'm looking forward to reading 😀

**Comment by stefaniebutland** [comment]
Thanks for agreeing to do this @mitchelloharawild. 
Here's info on formatting and pull request: https://github.com/ropensci/roweb2#contributing-a-blog-post. For Tech Note, in YAML use:
`categories:`
`  - technotes`

leave `topicid` blank and I'll add that just before publishing

**Comment by maelle** [comment]
Closing since the (very nice!) post has been published.
