### ISSUE TITLE
Bug when using in ioslides headers

### ISSUE THREAD

**Issue by sammerk** [mitchelloharawild/icons#17]
I think I have found a small bug (in your fancy package). Minimal example to reproduce:
```
---
title: "Untitled"
output: ioslides_presentation
---


## R Markdown `r icon::fa("rocket")` 

This is an R Markdown presentation.
```

This leads to a strange `">` line in the first line of the slide.

**Comment by mitchelloharawild** [comment]
Duplicate of #7. As far as we know, this is an issue with `rmarkdown::html_document`.
