### ISSUE TITLE
ideas-repec icon missing from ai?

### ISSUE THREAD

**Issue by JeffreyRacine** [mitchelloharawild/icons#18]
Greetings,

Great package, thanks for your contribution.

I am able to get many of the icons listed but ideas-repec that is listed in your link to academicons appears to be missing  `icon::ai("ideas-repec")`. It would be great to have this functionality added if it is no too much trouble. 

Thanks!

**Comment by mitchelloharawild** [comment]
Thanks, I've updated the academicons library to now include this icon.

**Comment by JeffreyRacine** [comment]
Thank U!
