### ISSUE TITLE
Add support for interactive sessions

### ISSUE THREAD

**Issue by pat-s** [mitchelloharawild/icons#22]
like `xaringan` which runs `servr` in an interactive R session in RStudio.

This causes icons not to be rendered. Instead the only the name is returned.
Is there any value in returning the name at all?

I removed the interactive condition and it works fine with `xaringan`.
As its one of the most used presentation libraries in R, it would be great if it could be supported!

Maybe there is even a simpler way to suppress the interactiveness of the server? cc @yihui

Cross-ref: https://github.com/earowang

https://github.com/ropenscilabs/icon/blob/993fc64a9d06758997f8458d06827f175e4144df/R/fa.R#L65-L66

**Comment by peterchristofferholm** [comment]
@pat-s 's temporary solution also works for me. In case anyone wonders how this can be accomplished, use `trace(fa, edit = TRUE )` and delete line 65 and line 66. YMMV!

**Comment by mitchelloharawild** [comment]
I've removed the interactive() bit with a better test for if the document is being knit.

**Comment by pat-s** [comment]
Thanks!
