### ISSUE TITLE
Icons not showing when using githubpages

### ISSUE THREAD

**Issue by YagizcanErdogan** [mitchelloharawild/icons#27]
Page : https://yagizcanerdogan.github.io/budgetapplicationv1/

If you press f12 for console you can see the error saying "http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" is blocked

**Comment by mitchelloharawild** [comment]
This should be fixed in the upcoming rewrite of the package: https://github.com/mitchelloharawild/icon

**Comment by mitchelloharawild** [comment]
Resolved by #31
