### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by maelle** [mitchelloharawild/icons#28]
:wave: @mitchelloharawild! I've started using your new package in a slidedeck, nice work!

Shouldn't this repo here be archived? Before doing that I'd recommend making the README a minimal README with a [moved status badge](https://www.repostatus.org/) and a few lines about where to find the new API.

**Comment by maelle** [comment]
Also, I'd recommend closing all open issues after a comment indicating the new status and where to find the new repo.

**Comment by mitchelloharawild** [comment]
Hi, yes!
My plans to PR the new repo into here, and then move the ropenscilabs repo onto my account so that it appropriately redirects.

**Comment by maelle** [comment]
Aaah ok even smarter. Thanks for the update!

**Comment by maelle** [comment]
:wave: @mitchelloharawild  re-pinging you about the transfer as we're cleaning up ropenscilabs cf https://devguide.ropensci.org/curationpolicy.html#incubator-packages

**Comment by mitchelloharawild** [comment]
Done, thanks!

**Comment by maelle** [comment]
Thank you! :rocket:
