### ISSUE TITLE
wrong ionicons

### ISSUE THREAD

**Issue by rickyars** [mitchelloharawild/icons#29]
when i check the icon names in `ii_iconList()` it doesn't match the names on the linked website for ionicons (https://ionicons.com/). also, many of the icons are not available. is there a way to sync the package with what's available on the website?

**Comment by rickyars** [comment]
it looks like the package is using ionicons 2.0.1. the current version is 5.0.1. 
https://github.com/ionic-team/ionicons

**Comment by mitchelloharawild** [comment]
Try using the rewrite of the icon package: https://github.com/mitchelloharawild/icon
It has support for updating the icon libraries independently of the package development, so you should be able to install whichever version of ionicons that you need.

**Comment by mitchelloharawild** [comment]
Resolved by #31
