### ISSUE TITLE
Not rendering (Ubuntu 16.04)

### ISSUE THREAD

**Issue by jonocarroll** [mitchelloharawild/icons#3]
There's a good chance I'm doing something wrong, but I can't get this to work at all.

````
---
title: "Testing icon"
author: "Jonathan Carroll"
date: "10 November 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Testing `icon`

`r icon::fa("birthday_cake")`

```{r}
icon::fa("birthday_cake")
```
````
renders to 

![fa_html](https://user-images.githubusercontent.com/9496865/32636448-c3430978-c604-11e7-9300-15767d55d91c.png)

and 

![fa_pdf](https://user-images.githubusercontent.com/9496865/32636452-c910e3d4-c604-11e7-8294-b42495979ee2.png)

I have `fonts-font-awesome` installed (4.5.0~dfsg-1).

Any hints?

**Comment by jonocarroll** [comment]
Disregard. Works with `"rocket"`... I was using `_` instead of `-`. My bad.

**Comment by mitchelloharawild** [comment]
This should be clearer now with changes made in #4.

```R
> icon::fa("birthday_cake")
Error in icon::fa("birthday_cake") : 
  Icon 'birthday_cake' not found in font awesome. Did you mean 'birthday-cake'?
```

**Comment by jonocarroll** [comment]
Awesome, cheers! I take it there's no way to get the icons to render in `README.md` (e.g. on GitHub)? Or am I still using it wrong?

**Comment by mitchelloharawild** [comment]
That is correct. As far as I know, github markdown doesn't support css.

**Comment by pat-s** [comment]
Hi guys, using this thread here as the question title matches.

I now tried it on Ubuntu 14.04 (VM), Kubuntu 16.04 & 17.10 (full install) and cannot get it to work.

I have installed `font-awesome` and tried it both with `xaringan` and `html_document()`. 
Tried within RStudio and command line.
What am I missing? :(
Would really love to get this working...

**Comment by earowang** [comment]
Am wondering if the following snippet works for you:

````html
---
output: html_document
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

<i class="fa fa-file"></i>
````

**Comment by pat-s** [comment]
Hehe, I am just about editing my comment with your snippet.

Yes, this works for me! Can this be used as a starting point to track down the problem?
Is this was `icon` actually does in the background?

**Comment by earowang** [comment]
Yep, just wrapping the `<i>` tags but we have implemented the `knit_print` S3 method for the `icon` class. 

What output do you get? Nothing?

**Comment by pat-s** [comment]
> What output do you get? Nothing?

No no, it works! However, using `icon` does not work. :thinking: 
Would of course be nice to track down the problem. 
Where can I look for some logs/paths? In the resulting html?

**Comment by earowang** [comment]
Yep, just inspect the elements in the html. Seems the `<i>` tag is not passed to the html in the `xaringan::infinite_moon_reader`, where I could reproduce the issue.

**Comment by pat-s** [comment]
Btw it works now with `html_document()` :thinking: 

Here'S the `xaringan` stuff:

RMD

```r
---
title: "Making RMarkdown Awesome"
subtitle: "Team Rocket"
author: "Timothy Hyndman <br> Mitchell O'Hara-Wild <br> Earo Wang"
date: "27/10/2017"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


\```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
\```

<i class="fa fa-rocket"></i>

<i class="fa fa-file-pdf-o" aria-hidden="true"></i>


\```{r}
icon::fa("rocket")
\```
```

HTML

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Making RMarkdown Awesome</title>
    <meta charset="utf-8">
    <meta name="author" content="Timothy Hyndman   Mitchell O’Hara-Wild   Earo Wang" />
    <link href="libs/remark-css-0.0.1/default.css" rel="stylesheet" />
    <link href="libs/remark-css-0.0.1/default-fonts.css" rel="stylesheet" />
    <link href="libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />
  </head>
  <body>
    <textarea id="source">
class: center, middle, inverse, title-slide

# Making RMarkdown Awesome
## Team Rocket
### Timothy Hyndman <br> Mitchell O’Hara-Wild <br> Earo Wang
### 27/10/2017

---

&lt;i class="fa fa-rocket"&gt;&lt;/i&gt;

&lt;i class="fa fa-file-pdf-o" aria-hidden="true"&gt;&lt;/i&gt;



\```r
icon::fa("rocket")
\```

\```
## [1] "fa:rocket"
\```
    </textarea>
<script src="https://remarkjs.com/downloads/remark-latest.min.js"></script>
<script>var slideshow = remark.create({
"highlightStyle": "github",
"highlightLines": true,
"countIncrementalSlides": false
});
if (window.HTMLWidgets) slideshow.on('afterShowSlide', function (slide) {
  window.dispatchEvent(new Event('resize'));
});
(function() {
  var d = document, s = d.createElement("style"), r = d.querySelector(".remark-slide-scaler");
  if (!r) return;
  s.type = "text/css"; s.innerHTML = "@page {size: " + r.style.width + " " + r.style.height +"; }";
  d.head.appendChild(s);
})();</script>

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre']
  }
});
</script>
<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
(function () {
  var script = document.createElement('script');
  script.type = 'text/javascript';
  script.src  = 'https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML';
  if (location.protocol !== 'file:' && /^https?:/.test(script.src))
    script.src  = script.src.replace(/^https?:/, '');
  document.getElementsByTagName('head')[0].appendChild(script);
})();
</script>
  </body>
</html>

```

**Comment by earowang** [comment]
```r
## [1] "fa:rocket"
```

the string is returned if it runs interactively in the console. Looks like it doesn't get to the function `knit_print()` in the rmd. Probably a server issue.
