### ISSUE TITLE
Problems downloading academicons

### ISSUE THREAD

**Issue by valentinaandrade** [mitchelloharawild/icons#40]
Hi @mitchelloharawild , first of all **thank you very much for the package**. I'm taking it for a xaringan presentation and at least fontawesome works great. 

It just happens that when I make `icon::download_academicons()` the following error appears. 

`Error: lexical error: invalid char in json text.
                                       NA
                     (right here) ------^`

Is it a problem of mine or a bug in the package?
Kindest Regards

**Comment by mitchelloharawild** [comment]
Fixed. This problem has been introduced by changes to the academicons repository structure.

Thanks for your bug report.

**Comment by valentinaandrade** [comment]
Thank you very much mitchell!!
