### ISSUE TITLE
Google Material Design Icons repository is restructured

### ISSUE THREAD

**Issue by tgerke** [mitchelloharawild/icons#41]
As of the 4.0.0 update, Google removed `package.json` from [the GitHub repository](https://github.com/google/material-design-icons) and this causes `download_material_design()` to fail as follows: 

```
> icon::download_material_design()
Error in open.connection(con, "rb") : 
  cannot open the connection to 'https://raw.githubusercontent.com/google/material-design-icons/master/package.json'
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open URL 'https://raw.githubusercontent.com/google/material-design-icons/master/package.json': HTTP status was '404 Not Found'
```

Looks like the download function only uses the json to capture version and license for Material design in the following:

```
meta <- jsonlite::read_json("https://raw.githubusercontent.com/google/material-design-icons/master/package.json")
install_icon_zip("material_design", url, svg_path = mdi_svg_paths, 
    svg_pattern = "_48px\\.svg", svg_dest = mdi_svg_dest, 
    meta = list(name = "Material Design Icons", version = meta$version, licence = meta$license))
```

One way to assign version would be to use the [`gh` package](https://github.com/r-lib/gh) which I do recognize introduces a (lightweight) dependency, but a line to do that is here:

```
gh::gh("GET /repos/{owner}/{repo}/releases/latest", owner="google", repo="material-design-icons")$tag_name
```

Conveniently, the same thing will work for license: 

```
gh::gh("GET /repos/{owner}/{repo}", owner="google", repo="material-design-icons")$license$name
```

**Comment by mitchelloharawild** [comment]
Thanks, the code has been updated to support v4.0.0.

Note that this new structure makes it simple to obtain all variants of the icons, so the code should now also specify the icon variant.

For example the `outlined` style specified below is now required (previously, `filled` was the only style provided).

```r
library(icon)
material_design$outlined$alert$add_alert
```
