### ISSUE TITLE
size and color of icon with new API

### ISSUE THREAD

**Issue by lionelvoirol** [mitchelloharawild/icons#43]
Hi,

I used to integrate icon on xaringan presentation with for example the following syntax:

``r icon::fa("r-project", size = 1, color = "#246ABE")``

Since the new changes on the API discussed here (https://github.com/mitchelloharawild/icon/pull/31), I understood that I should use `icon::fontawesome()`, however, the what is the appropriate syntax for the color and size argument? It is not specified in the doc and the arguments are no longer supported.

Could you please explain these changes for the customization of icons?

Thanks

**Comment by mitchelloharawild** [comment]
Try out the icon_style() function. I will add a mention to the
documentation with more details on how to migrate tomorrow.

**Comment by mitchelloharawild** [comment]
Thanks, added an example to the README. For your particular example, it would become:

```r
library(icon)
library(magrittr)
fontawesome("r-project") %>% icon_style(scale = 1, fill = "#246ABE")
```

**Comment by lionelvoirol** [comment]
great. thanks a lot!
