### ISSUE TITLE
Package name conflict with {ICON}

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/icons#48]
A package named "ICON" was published on CRAN on `2019-12-06`. The repository for this package is here: https://github.com/rrrlw/ICON

Unfortunately this disallows submitting this package to CRAN under the `{icon}` name, as per the CRAN policy.
>  Packages should be named in a way that does not conflict (irrespective of case) with any current or past CRAN package (the Archive area can be consulted), nor any current Bioconductor package. Package maintainers give the right to use that package name to CRAN when they submit, so the CRAN team may orphan a package and allow another maintainer to take it over.
> 
> When a new maintainer wishes to take over a package, this should be accompanied by the written agreement of the previous maintainer (unless the package has been formally orphaned).
*https://cran.r-project.org/web/packages/policies.html#Source-packages*

This conflict has arisen from two issues:
* The `{icon}` package not being promptly submitted to CRAN.
* The `{ICON}` package not checking package name availability using `available::available()` (https://r-pkgs.org/workflows101.html#use-the-available-package)

---

The short `{icon}` name is a design feature of the package, as the `icon::library$name` interface is promoted and widely used. A change of package name is likely disruptive to many users.

I foresee three options (in no particular order) going forward:

1. Don't submit `{icon}` to CRAN (hasn't been on CRAN for >3 years, but this has caused installation troubles for new users. Much like `{hadley/emo}`.)
2. Rename `{ICON}` package and submit `{icon}` to CRAN (could be difficult with CRAN maintainers, and existing users of `{ICON}`).
3. Rename the `{icon}` package (Alternative appropriate package names are in short supply... perhaps `{icons}`?)

If either package were to be renamed, this would inevitably cause disruption to the package's users.

---

Perhaps the `{ICON}` maintainer @rrrlw could weigh in on the feasibility of changing `{ICON}` name.

**Comment by storopoli** [comment]
`icons` would be nice.

**Comment by IndrajeetPatil** [comment]
The function `fa` also conflicts with the identically named function in https://github.com/rstudio/fontawesome

**Comment by mitchelloharawild** [comment]
The `fa()` function in `{icon}` is deprecated in favour of `fontawesome()`.

**Comment by IndrajeetPatil** [comment]
Perfect!

**Comment by mitchelloharawild** [comment]
Package is now named {icons} to avoid trouble and complexity with CRAN and the {ICON} package.
