### ISSUE TITLE
Having trouble with icon and .Rpres

### ISSUE THREAD

**Issue by softloud** [mitchelloharawild/icons#5]
Hiya icon :rocket: peeps,

I'm giving a talk using .Rpres and I'd love to use `icon` and promote the superfun of the unconf far and wide. 

When I render a my presentation with this `r icon::fa("rocket")` inline, I'm getting this:
![screen shot 2017-11-13 at 4 34 21 am](https://user-images.githubusercontent.com/13408706/32701543-f053efbc-c82b-11e7-8c86-1a5b6cf43d93.png)

The strange part is that's where I load the `tidyverse`.

Cheers! :notes:

**Comment by mitchelloharawild** [comment]
Hi there! :smile: 

`icon` is designed to work with documents created with RMarkdown, as part of the library management (ensuring the icon fonts are loaded) depends on the YAML header (hence the error).

If using the .Rpres format is not essential for your presentation, I would recommend changing your slides to use the RMarkdown format (https://stackoverflow.com/questions/25791967/convert-rstudio-presentation-rpres-to-rmarkdown-presentation-rmd). That way you can include all of the rockets you need! :rocket: :rocket: :rocket:

**Comment by softloud** [comment]
Thanks! Of course, .Rpres defaults to revealjs, right? I’ll investigate rmarkdown - but I am love with these whoosh transitions ;)

**Comment by mitchelloharawild** [comment]
Not sure which transition you're is the "whoosh" one (they all kind of whoosh if you ask me!) but you can play with the transition parameter in the YAML header for revealjs_presentation.

The supported revealjs features are neatly summarised here: http://rmarkdown.rstudio.com/revealjs_presentation_format.html

And a quick sample :rocket: presentation is below.

```R
---
title: "Rockets"
author: ropenscilabs/icon
date: November 13, 2017
output: 
  revealjs::revealjs_presentation:
    highlight: pygments
    theme: simple
    center: true
    transition: slide
---

## It's a rocket

Whoosh

`r icon::fa_rocket(size=4, animate="spin")`
```
