### ISSUE TITLE
Rough migration due to name change

### ISSUE THREAD

**Issue by BerriJ** [mitchelloharawild/icons#53]
Hi there,
it's not really in issue in the classical sense but I just wanted to propose creating a separate repository "mitchelloharawild/icon" containing the old icons package. There are some packages that depend on the "icon" package. Due to the name change installing "icon" leads to an error message now (see https://github.com/nstrayer/datadrivencv/issues/57). 

Ideally, the old package itself would tell the users about its deprecation.

Just a suggestion. Since I do not expect all packages depending on "icon" to merge fixes soon my current workaround is to install v.1.0.1. manually:

`remotes::install_github('mitchelloharawild/icons@v0.1.0')`

Anyway, thanks for this wonderful package .
BerriJ

**Comment by mitchelloharawild** [comment]
Thanks for bringing this to my attention, unfortunately a breaking change is necessary if the package is to be put on CRAN (https://github.com/mitchelloharawild/icons/issues/48).

I'd prefer not to create the "mitchelloharawild/icon" repo, as that would break the GitHub redirects from "ropenscilabs/icon" -> "mitchelloharawild/icon" -> "mitchelloharawild/icons". So anywhere the package has been linked to in the past three years would be linked to the defunct separate repository.

I think this is a situation where the band-aid just needs to be ripped off, and have the package submitted to CRAN asap to ensure less breaking changes going forward.
