### ISSUE TITLE
feather icons

### ISSUE THREAD

**Issue by datalorax** [mitchelloharawild/icons#55]
Hi - really great work on this package! I was wondering if you had considered adding support for [feather icons](https://feathericons.com)?

**Comment by mitchelloharawild** [comment]
Thanks for your suggestion and kind words! Supporting feather icons has been planned for the package for a while. I'm pleased to say that I've now added feather icons to the package :smile:

**Comment by datalorax** [comment]
Wow! That was quick! 😂 Thanks so much!
