### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by piyayut-ch** [mitchelloharawild/icons#56]
Thank you for this great package.
Previously, I was able to install the package using `remotes::install_github("mitchelloharawild/icons")` but after I upgrade R, I could not install it. Please kindly suggest how to fix it.

Thanks

Here is the error message

*** installing help indices
  converting help for package 'icons'
    finding HTML links ... done
    academicons                             html
    feather_icons                           html
    fontawesome                             html
    google_material                         html
    icon_find                               html
    icon_installed                          html
    icon_save                               html
    icon_set                                html
    icon_style                              html
    icons-package                           html
    ionicons                                html
    migration                               html
    octicons                                html
    read_icon                               html
    simple_icons                            html
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'icons':
 .onAttach failed in attachNamespace() for 'icons', details:
  call: NULL
  error: invalid version specification 'v4.28.0'
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'icons':
 .onAttach failed in attachNamespace() for 'icons', details:
  call: NULL
  error: invalid version specification 'v4.28.0'
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'

**Comment by mitchelloharawild** [comment]
Thanks for the bug report, I can reproduce this error.

**Comment by mitchelloharawild** [comment]
Fixed, thanks. This was due to an version number in the new `feather_icons()` icon set.
I've made package loading more robust to this, and will work on fixing the feather icons version format later.

**Comment by piyayut-ch** [comment]
> Fixed, thanks. This was due to an version number in the new `feather_icons()` icon set.
> I've made package loading more robust to this, and will work on fixing the feather icons version format later.

Thank you very much
