### ISSUE TITLE
Investigate possibility of passing {icons} icons to the shiny `icon=` argument

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/icons#59]
Related: https://community.rstudio.com/t/use-of-open-source-icons-in-shiny/110056/5

**Comment by Moohan** [comment]
This worked for me (and was the motivation behind Tom Jemmett doing #73)

I tried something like this in our existing Shiny Dashboard and it seemed to work fine.

```r
 tabPanel(
        title = "Home",
        icon = icons::health_icons("blood_bag"),
        ...)
```

This was a direct swap for `icon = icon("building")` i.e. `shiny::icon` that was there before.

**Comment by mitchelloharawild** [comment]
Thanks! I'm closing this since this is a limitation of shiny's `validateIcon()` function which is used in `actionButton()`.
The equivalent result for buttons can be obtained with `actionButton("rocket", list(fontawesome$solid$rocket, "Rocket"))`.

**Comment by mitchelloharawild** [comment]
Minimal example:

```r
library(shiny)
library(icons)

ui <- fluidPage(
  actionButton("d1", "Rocket", icon = icon("rocket")),
  actionButton("rocket", list(fontawesome$solid$rocket, "Rocket"))
)

server <- function(input, output) {}
shinyApp(ui = ui, server = server)
```
