### ISSUE TITLE
Not working with custom css?

### ISSUE THREAD

**Issue by pat-s** [mitchelloharawild/icons#6]
When using a custom css file with `xaringan`,  icons do not render for me, only the code gets printed.

Everything works fine with the default `xaringan` template. Anything crucial that is missing in my custom css? [Its quite large so I would only post it if it really helps)

**Comment by earowang** [comment]
I couldn't replicate the issue. The icons render as expected when I use a custom css fill in `xaringan`. Which version of `xaringan` do you use?

**Comment by pat-s** [comment]
Thanks for looking into this, @earowang!

[Here's](https://github.com/ropenscilabs/icon/files/1509811/test.zip) a reprex with my custom css. Wondering if it works for you :smile: If yes, it might be an OS problem? However, the default template works for me so this is mysterious :thinking:

**Comment by earowang** [comment]
Seems not a problem on a macOS machine. which OS do you use? 

<img width="1092" alt="screen shot 2017-11-29 at 10 37 54 am" src="https://user-images.githubusercontent.com/2456216/33350166-863e73f4-d4f1-11e7-95c8-549e1d86bf82.png">

**Comment by mitchelloharawild** [comment]
I also cannot reproduce this on Ubuntu 16.04 and Windows 10.

**Comment by pat-s** [comment]
I'm using Arch KDE. Tested it on a second machine to verify this. On the second machine the default template does not even work for me.

Wondering what library I might be missing here :thinking:

**Comment by earowang** [comment]
Interestingly, I've had the same problem when using `xaringan::infinite_moon_reader` in RStudio. But it appears perfect if using the infinite moon reader in the terminal.

**Comment by pat-s** [comment]
Tried it using the terminal but did not help either. Even on 16.04 I cannot get it to work.
Am I missing a specific library? 

Here's the full render call, maybe it helps somehow:

```
/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS 2017_12_Vitoria.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output 2017_12_Vitoria.html --smart --email-obfuscation none -V 'mathjax-url=https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML' --standalone --section-divs --template /home/pjs/R/x86_64-pc-linux-gnu-library/3.4/xaringan/rmarkdown/templates/xaringan/resources/default.html --no-highlight --include-in-header /tmp/RtmpYxWV2Y/rmarkdown-str652c7a26100d.html --include-before-body /tmp/RtmpYxWV2Y/xaringan652c54075c5e.md --include-after-body /tmp/RtmpYxWV2Y/xaringan652c5a5fada2.js --variable title-slide=true --variable math=true
```

**Comment by peterchristofferholm** [comment]
I have the same issue as @pat-s on my machine (macOS). When using a custom css, the icon does not render at all. I have this problem in infinite-moonreader rendered slideshows. However, there are no missing icons if I just knit to moonreader.

**Comment by peterchristofferholm** [comment]
I think this issue can be closed.
