### ISSUE TITLE
Add style and class options for svg

### ISSUE THREAD

**Issue by kylebutts** [mitchelloharawild/icons#61]
Hi! I just started using this package and it's awesome. I was wondering if it would be possible to pass custom style or class options to the svg tag? It currently doesn't seem supported but perhaps a regex str insert could work? Would be happy to help with this if you are interested

**Comment by mitchelloharawild** [comment]
Custom style attributes should be possible with `icon_style()`. This might need generalising to support adding classes.

**Comment by kylebutts** [comment]
Awesome, that definitely would do it! Thank you
