### ISSUE TITLE
The vignette link on the readme page is broken.

### ISSUE THREAD

**Issue by Nowosad** [mitchelloharawild/icons#9]

**Comment by mitchelloharawild** [comment]
Thanks for letting me know 👍 
Resolved! 🚀

**Comment by earowang** [comment]
still 404.

**Comment by Nowosad** [comment]
https://github.com/ropenscilabs/icon/pull/10 - this should fix the issue.

**Comment by mitchelloharawild** [comment]
Ah, thanks. Was committing to the *.Rmd without changing the *.md
Merged.

**Comment by Nowosad** [comment]
Thanks for the package!

**Comment by trafficonese** [comment]
Link is broken again
